[gcp_service_account]
type = "service_account"
project_id = "cafe-order-2026"
private_key_id = "1b1c9400fdccedccfcbd35786a6eff0c3ab24f30"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPW54d5wBZzKUF
N8rhNbteGEz7zwsGMaRIUhC34ryfRemqhtNnMbfHRjF4kPFoaTrEmkG7iWdOQjYJ
Sz59o+O/Q3hkG0rXAi38MbswtJJlgkQpWII+jklt/6yOFoBIBheXXfouoEp0lez2
7IhIa0EqxPaVymEN1e9n4S1doBR0nZ+nAIaSfWsOXiHn3++5aTvWLcRDUlw5XtA3
80knsmea6SkxPkqYbQERy85wQSrEFtLjTohSYV7ntR5bvgKK1Y1NHAndeluFYvFa
F1awCXOC3k/WBW4WrAFV/sltMYSoGUJPCK65iznbVJ0sSr3QAgBOVXZ2qYL1kotO
m4LoY1JrAgMBAAECggEAMhukqPsyhYDDe/BQkX2nioR6zfrpYhTK60MRkS40gJSn
c7LjETPdgkU/HTCBdcbAEdRpAAWjNjEf170cG8Zn+cc3J5HE0xJOxHvMDWgFXIxP
JmKiDrXZnsBDFY7wbvcx6j0mgO/xLh0wxza/dCie9dPk9quSKoLBOKwch1xwtQEW
nH2Pe+cGux7Jb79++Muq9iVmcxLx5WszpQuBOZHSVUKE8DZynSSKaFQXE5JRzWYd
wBsAy1kpwAFBqH/K/vmBJruUlf7RSNwP3SHjZsOfY1M5GZuAFJ0bnTKQpIp6NBKK
25HEAW3VinKni6h25h6mrXjDdOUgXsORcmimH7K6YQKBgQDyiawlNzLsmjcJ+2ox
pjs3KhpbN9n0wC9kJqGJu4l4nvQeEhcfO01SbWrisXby0doHHnSB3NNaCZScsFNJ
hbAftt9N4gl73J0fW5jhGrHUFTrMSI6YtDkxR9KVbygoulLTrQHVNqqGl6kbFUft
ICJ9rcvdW+L2i9+cfSPbASiUsQKBgQDa3g7rzLGx99qoaTx1mpz+IORgrhSi44wX
3KLft+QCSJSFXQJM8cWJ/7eW3rmUPCTJ/Lyn13cD3N20DxCYvjUfN3fTxG0N5T07
tT1bA6ZPWWxJ2PGLbef8nc8hJIGtSvwZmtsRAF3hR9ZYPAcni+n42oNX7yM/pgru
EzUlUcHP2wKBgEQNtzzWCTb0ap8laX227ASljrGrsT+IsYODh24TLhanW04Yu14r
EJ4hT41+SCcIFQpMVFqf8Lnh2E5C94u4tFuhv3SmCQ01MO08kWAQUnd04YOylDhq
0WVvhrohb35GEbmNYOdHqH+NjIip5v21N5hWLM7W2o9dXggV4Pqxj4ZxAoGBAJ+5
HCSC7k7VdVIf8opUuitPL7tKby7sZmlnj8k6NwBfnVuyI6KpciKiZoWIpuACAEsT
0U2flXBRN85WjCMb9EKCxUTa/Ub9u3Eec9c+05jmxnsiAixhmcImHGmwbZ5csZuy
AhrnLJviRA+CRypaFfaQ6Pc8QnoJn8JcbBV/E7SvAoGBALLwjLEFlRUIt1Y0XuPg
/AOngH7NOtMPhBmLgL+XzL4QW9gGvm7OmgTbyIVzWfTeNO6xT9cg3/opDZ/VMjSB
fBTUPBKDCykqlkyfCul6ZcvwvDlLvgWLhh6/mmiVv6lwoT4qRYbAOfphHncvGk8Y
4/36n7sru/m9dray/ltUmX1B
-----END PRIVATE KEY-----
"""
client_email = "cafe-order@cafe-order-2026.iam.gserviceaccount.com"
client_id = "115907687837401839888"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cafe-order%40cafe-order-2026.iam.gserviceaccount.com"

SHEET_ID = "1MFEWWArKM5_8lXIZNqDkb22HfeVx3OURAG--Eb7GIv4"
